### ISSUE TITLE
Feature Request: Allow Markdown in React Components

### ISSUE THREAD

**Issue by clintandrewhall** [andreypopp/reactdown#1]
I've been trying to figure this out without much success: I'd like to have reactdown continue to process markdown (and thus, create markup) inside React component tags.  For example:

https://raw.githubusercontent.com/clintandrewhall/metaphorically/master/metaphors/open-source.md

Right now, and due to Markdown rules, this content (e.g. the numbered list) isn't being converted.  How difficult would it be to implement?  Do you have any pointers?  Thanks in advance!

**Comment by andreypopp** [comment]
This will be possible with the redesigned version.
