### ISSUE TITLE
Consider resolving `components` relative to config file

### ISSUE THREAD

**Issue by nevir** [andreypopp/reactdown#17]
reactdown (in webpack) currently searches for config files relative to the working directory, but it resolves the `components` module relative to the `.md` file being rendered.

This is a bit confusing (I would have expected the `components` module to be resolved relative to the `.reactdownrc`).  Also, it makes it painful to have `.md` files organized into directories (unless they're all the same directory depth)

---

I'm currently working around this by specifying a webpack [`resolve.alias`](https://webpack.github.io/docs/configuration.html#resolve-alias), and pointing the `.reactdownrc` to that aliased module name

**Comment by andreypopp** [comment]
Yep, fixed in `schema` branch which I'll merge soon.

**Comment by nevir** [comment]
Awesome!
